#- name: Single Branch play
#  ansible.builtin.include_tasks:
#    file: single_job.yml
#  loop: "{{single_jobs}}"

- name: Multi Branch play
  ansible.builtin.include_tasks:
    file: multi_job.yml
  loop: "{{multi_jobs}}"