- name: Replacing the xml File
  ansible.builtin.template:
    src: single_job_config.xml
    dest: /tmp/test.xml

- name: Create jenkins Job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/test.xml') }}"
    name: "{{item.job_name}}"
    password: admin123
    url: http://172.31.94.118:8080
    user: admin